import Head from "next/head";
import { Form, Button, Alert, Row, Container } from "react-bootstrap";
import { useFormik } from "formik";
import { useContext, useEffect, useState } from "react";
import { useRouter } from "next/router";
import { AuthContext } from "../context/authContext";

export default function Home() {
  const router = useRouter();
  const auth = useContext(AuthContext);
  const [serverErrors, setServerErrors] = useState<any>();

  useEffect(() => {
    if (auth.token) {
      router.push("/schools");
    }
  }, []);

  const formik: any = useFormik({
    initialValues: {
      username: "",
      password: "",
    },

    onSubmit: async (values) => {
      try {
        // API call save the student data
        await auth.login(values);
        router.push("/schools");
      } catch (error: any) {
        // console.log(error.response.data["detail"]);
        setServerErrors(error.response.data["detail"]);
      }
    },
  });

  return (
    <>
      <Head>
        <title>Next SMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className="d-flex justify-content-center align-items-center vh-100">
          <Form onSubmit={formik.handleSubmit}>
            <h4 className="text-primary">School Management System</h4>
            <br />
            <br />
            {serverErrors && <Alert variant="danger">{serverErrors}</Alert>}
            <Form.Group className="mb-3" controlId="formBasicUsername">
              <Form.Label>Username</Form.Label>
              <Form.Control
                type="text"
                name="username"
                placeholder="username"
                value={formik.values.username}
                onChange={formik.handleChange}
              />
              <Form.Text className="text-danger">
                {formik.errors &&
                  formik.errors.username &&
                  formik.errors.username}
              </Form.Text>
            </Form.Group>

            <Form.Group className="mb-3" controlId="formBasicPassword">
              <Form.Label>Password</Form.Label>
              <Form.Control
                type="password"
                name="password"
                placeholder="password"
                value={formik.values.password}
                onChange={formik.handleChange}
              />
              <Form.Text className="text-danger">
                {formik.errors &&
                  formik.errors.password &&
                  formik.errors.password}
              </Form.Text>
            </Form.Group>
            <Button variant="primary" type="submit">
              Login
            </Button>
          </Form>
        </div>
      </Container>
    </>
  );
}
